services:
  waha:
    image: devlikeapro/waha:latest

    # Add "dns" if you have a problem with resolving "web.whatsapp.com"
    # dns:
    #   - 1.1.1.1
    #   - 8.8.8.8
    ports:
      - '3000:3000'
    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      - waha_sessions:/app/.sessions

      # Save media files
      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - waha_media:/app/.media
    environment:
      WAHA_API_KEY: ${WAHA_API_KEY}
      WAHA_DASHBOARD_USERNAME: ${WAHA_DASHBOARD_USERNAME}
      WAHA_DASHBOARD_PASSWORD: ${WAHA_DASHBOARD_PASSWORD}
      WHATSAPP_SWAGGER_USERNAME: ${WHATSAPP_SWAGGER_USERNAME}
      WHATSAPP_SWAGGER_PASSWORD: ${WHATSAPP_SWAGGER_PASSWORD}
      WAHA_DASHBOARD_ENABLED: ${WAHA_DASHBOARD_ENABLED}
      WHATSAPP_SWAGGER_ENABLED: ${WHATSAPP_SWAGGER_ENABLED}
      WHATSAPP_DEFAULT_ENGINE: ${WHATSAPP_DEFAULT_ENGINE}
      WAHA_BASE_URL: ${WAHA_BASE_URL}
      WAHA_LOG_FORMAT: ${WAHA_LOG_FORMAT}
      WAHA_LOG_LEVEL: ${WAHA_LOG_LEVEL}
      WAHA_PRINT_QR: ${WAHA_PRINT_QR}
      WAHA_MEDIA_STORAGE: ${WAHA_MEDIA_STORAGE}
      WHATSAPP_FILES_LIFETIME: ${WHATSAPP_FILES_LIFETIME}
      WHATSAPP_FILES_FOLDER: ${WHATSAPP_FILES_FOLDER}
      WHATSAPP_HOOK_URL: ${WHATSAPP_HOOK_URL}
      WHATSAPP_HOOK_EVENTS: ${WHATSAPP_HOOK_EVENTS}


    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

    networks:
      - n8n


networks:
  n8n:
    external: true

volumes:
  waha_sessions:
    driver: local
  waha_media:
    driver: local
